name: Build and Deploy

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Publish Docker Action
      uses: jerray/publish-docker-action@v1.0.3
      with:
        # Username used to login docker registry
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        # Password used to login docker registry
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        # Static image tag list, separated by comma
        tags: latest,${{ github.sha }}

    - name: Echo Full Image name
      run: |
        echo ${{ github.sha }}
        echo "ragingprodigy/movie-api:${{ github.sha }}"

    - name: Deploy to Server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: ${{ secrets.SSH_LOGIN }}
        privateKey: ${{ secrets.SERVER_PRIVATE_KEY }}
        debug: true
        command: |
          cd /home/movies-api/
          sed -i "s_movies.*_movies-api:${{ github.sha }}_" docker-compose.yml
          docker-compose up -d

#    - name: Deploy to Server
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.SERVER_ADDRESS }}
#        username: ${{ secrets.SERVER_USERNAME }}
#        key: ${{ secrets.SERVER_PRIVATE_KEY }}
#        port: ${{ secrets.SERVER_PORT }}
#        script: |
#          cd /home/movies-api/
#          sed -i "s_movie-api.*_movie-api:${{ github.sha }}_" docker-compose.yml
#          docker-compose up -d
